### ISSUE TITLE
Deprecated NumPy module causing compatibility issues

### ISSUE THREAD

**Issue by cgobat** [japs/astrotools#2]
Running `astro_align.py` returns this error message:

    numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
    from numpy.core.umath_tests import inner1d
    Traceback (most recent call last):
    File "c:/<FILEPATH>/astrotools-master/astro_align.py", line 102, in <module> args.reference_frame = args.filenames[0]
    IndexError: list index out of range

Not sure what this is trying to do, otherwise I would fix it myself. Any pointers?

**Comment by japs** [comment]
Did you try providing the script with the input files it requires?

**Comment by cgobat** [comment]
Yes, but it seems that doing so merely fixes the `IndexError`, not the numpy issue. Looks like there's also an issue with an ALiPy call later on.

    numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
      from numpy.core.umath_tests import inner1d
    Traceback (most recent call last):
      File "astro_align.py", line 113, in <module>
        identifications = alipy.ident.run(args.reference_frame, fnames,
    AttributeError: module 'alipy' has no attribute 'ident'

Thanks for your help, this is a cool project!
